---
- hosts: all
  tasks:
    - name: Detect user “jf”
      userdetect: user=jf
      register: user

    - name: User “lol” can’t be found.
      userdetect: user=lol
      register: user

    - name: Detect fallback user “root”.
      userdetect: user=lol
                  fallback=root
      register: user

    - name: User and fallback user can’t be found.
      userdetect: user=lol
                  fallback=troll
      register: user

    - name: Detect users as a list
      userdetect:
        user:
          - jf
          - root
      register: user

    - name: Can’t detect users as a list
      userdetect:
        user:
          - lol
          - troll
      register: user
